//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoFinal3 {

    public partial class Backoffice {
        protected global::System.Web.UI.WebControls.GridView gvCategories;
        protected global::System.Web.UI.WebControls.TextBox txtNewCategory;
        protected global::System.Web.UI.WebControls.Button btnAddCategory;

        protected global::System.Web.UI.WebControls.DropDownList ddlAreaCategory;
        protected global::System.Web.UI.WebControls.TextBox txtNewArea;
        protected global::System.Web.UI.WebControls.Button btnAddArea;
        protected global::System.Web.UI.WebControls.GridView gvAreas;

        protected global::System.Web.UI.WebControls.DropDownList ddlTopicArea;
        protected global::System.Web.UI.WebControls.TextBox txtNewTopic;
        protected global::System.Web.UI.WebControls.Button btnAddTopic;
        protected global::System.Web.UI.WebControls.GridView gvTopics;

        protected global::System.Web.UI.WebControls.DropDownList ddlEnrollCourse;
        protected global::System.Web.UI.WebControls.DropDownList ddlEnrollStudent;
        protected global::System.Web.UI.WebControls.Button btnEnroll;
        protected global::System.Web.UI.WebControls.Label lblEnrollMessage;
    }
}
