//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoFinal3 {

    public partial class CourseCreate {
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.DropDownList ddlTrainer;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlArea;
        protected global::System.Web.UI.WebControls.DropDownList ddlTopic;
        protected global::System.Web.UI.WebControls.TextBox txtStart;
        protected global::System.Web.UI.WebControls.TextBox txtEnd;
        protected global::System.Web.UI.WebControls.TextBox txtSlots;
        protected global::System.Web.UI.WebControls.Button btnCreate;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
