//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoFinal3 {


    public partial class Notifications {

        protected global::System.Web.UI.WebControls.Repeater rptNotifications;
    }
}
